# Generated by Django 3.2.9 on 2021-11-22 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_students_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='address',
        ),
    ]
