# Generated by Django 3.2.9 on 2021-11-22 21:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_students_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='dept',
            new_name='Dept',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='name',
            new_name='Email',
        ),
        migrations.AddField(
            model_name='students',
            name='Name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
